### ISSUE TITLE
support 2023 protector version ?

### ISSUE THREAD

**Issue by tonzsm** [puff/EazyDevirt#19]
now this project support last version protector ?

**Comment by puff** [comment]
No, https://github.com/puff/EazyDevirt#support
There is [a PR](https://github.com/puff/EazyDevirt/pull/16) to add support for multiple versions, but it is unfinished.

**Comment by tonzsm** [comment]
> No, https://github.com/puff/EazyDevirt#support There is [a PR](https://github.com/puff/EazyDevirt/pull/16) that would add basic support for more versions, but it is unfinished.

thanks
